version: '3.9'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: tokennect-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tokennect
    ports:
      - "5464:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local

